# output and return - everything is currently supported
outputType:
  - summary
  - yearly

# These allow defining funs internally as lists. if aggregation_def is NULL, these need to have values and vice versa
# These allow defining funs internally as lists. if aggregation_def is NULL, these need to have values and vice versa
aggregation_sequence:
  all_time:
  - all_time
  ewr_code:
  - ewr_code_timing
  - ewr_code
  planning_units:
  - planning_units
  env_obj:
  - ewr_code
  - env_obj
  sdl_units: sdl_units
  Specific_goal:
  - env_obj
  - Specific_goal
  cewo_valleys: cewo_valleys
  Objective:
  - Specific_goal
  - Objective
  basin: basin
  target_5_year_2024:
  - Objective
  - target_5_year_2024

aggregation_funsequence:
  all_time:
  - ArithmeticMean
  ewr_code:
  - CompensatingFactor
  planning_units:
  - ArithmeticMean
  env_obj:
  - ArithmeticMean
  sdl_units:
  - SpatialWeightedMean
  Specific_goal:
  - list(mean = ~mean(., na.rm = TRUE))
  cewo_valleys:
  - SpatialWeightedMean
  Objective:
  - ArithmeticMean
  basin:
  - SpatialWeightedMean
  target_5_year_2024:
  - ArithmeticMean

agg_groups: scenario

# Setting `auto_ewr_PU = TRUE` (as in the default yaml) is easier than passing pseudo_spatial, but we can do the group_until and pseudo-spatial explicitly
# auto_ewr_PU: TRUE
auto_ewr_PU: FALSE

agg_group_until:
  planning_unit_name: planning_units
  gauge: planning_units

agg_pseudo_spatial: planning_units
